services:
  - type: web
    name: social-care-backend
    runtime: node
    plan: free
    buildCommand: cd backend && npm ci && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false

  - type: web
    name: social-care-frontend
    runtime: static
    buildCommand: cd frontend && npm ci && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20
      - key: GENERATE_SOURCEMAP
        value: false

databases:
  - name: social-care-db
    databaseName: socialcare
    user: socialcare_user
    plan: free